[project]
name = "snac-deep-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "tensorflow==2.18",
    "pillow>=10.0",
    "numpy>=1.26",
    "matplotlib>=3.8",
    "scikit-learn>=1.4",
    "ipykernel>=6.0",
    "pygments>=2.20.0",
    "tensorflow-metal==1.2.0",
    "marimo[recommended]>=0.23.14",
    "matplotlib-fontja>=1.1.0",
]

[dependency-groups]
dev = [
    "ruff>=0.15.17",
]
